# Generated by Django 5.2.9 on 2025-12-31 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[("training", "Entrenamiento"), ("event", "Evento")],
                        max_length=20,
                    ),
                ),
                (
                    "training_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mentors", "Mentores"),
                            ("mentees", "Mentees"),
                            ("facilitators", "Facilitadores"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "event_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("talk", "Charla"),
                            ("workshop", "Workshop"),
                            ("meeting", "Encuentro"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mentor", "Mentor"),
                            ("mentee", "Mentee"),
                            ("facilitator", "Facilitador"),
                            ("participant", "Participante"),
                            ("client", "Cliente"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Creada"),
                            ("scheduled", "Programada"),
                            ("rescheduled", "Reprogramada"),
                            ("completed", "Realizada"),
                            ("closed", "Cerrada"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("has_modules", models.BooleanField(default=False)),
                ("requires_module_survey", models.BooleanField(default=False)),
                ("provides_certification", models.BooleanField(default=False)),
                (
                    "modality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("online", "Online"),
                            ("in_person", "Presencial"),
                            ("hybrid", "Híbrido"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("requires_satisfaction_survey", models.BooleanField(default=False)),
                (
                    "provides_participation_certificate",
                    models.BooleanField(default=False),
                ),
                ("meeting_url", models.URLField(blank=True, null=True)),
                (
                    "location_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("invitations_sent", models.BooleanField(default=False)),
                ("confirmed_count", models.IntegerField(default=0)),
                ("attendance_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["start_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("active", "Activo"),
                            ("completed", "Completado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("mentor", "Mentor"),
                            ("mentee", "Mentee"),
                            ("facilitator", "Facilitador"),
                            ("participant", "Participante"),
                            ("client", "Cliente"),
                        ],
                        max_length=20,
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=160)),
                ("goals", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("availability_hours", models.PositiveIntegerField(default=2)),
                ("timezone", models.CharField(default="UTC", max_length=60)),
                ("requires_match", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_published", models.BooleanField(default=False)),
                ("materials_url", models.URLField(blank=True, null=True)),
                ("survey_sent", models.BooleanField(default=False)),
                ("survey_responses", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="programs.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("activity", "order")},
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("skill", "Desarrollo de Habilidad"),
                            ("career", "Crecimiento de Carrera"),
                            ("project", "Proyecto Específico"),
                            ("leadership", "Liderazgo"),
                            ("technical", "Técnico"),
                            ("soft_skill", "Habilidad Blanda"),
                            ("other", "Otro"),
                        ],
                        default="skill",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "Alta"),
                            ("medium", "Media"),
                            ("low", "Baja"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "specific",
                    models.TextField(help_text="¿Qué quiero lograr exactamente?"),
                ),
                ("measurable", models.TextField(help_text="¿Cómo mediré el progreso?")),
                (
                    "achievable",
                    models.TextField(
                        help_text="¿Es realista con los recursos disponibles?"
                    ),
                ),
                (
                    "relevant",
                    models.TextField(help_text="¿Por qué es importante este objetivo?"),
                ),
                ("time_bound", models.DateField(help_text="¿Cuál es la fecha límite?")),
                (
                    "progress_percentage",
                    models.IntegerField(default=0, help_text="0-100"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "No Iniciado"),
                            ("in_progress", "En Progreso"),
                            ("blocked", "Bloqueado"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="programs.match",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("progress_before", models.IntegerField()),
                ("progress_after", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="programs.goal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KeyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                (
                    "target_value",
                    models.FloatField(help_text="Valor objetivo a alcanzar"),
                ),
                (
                    "current_value",
                    models.FloatField(default=0, help_text="Valor actual"),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unidad de medida (%, horas, proyectos, etc.)",
                        max_length=50,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_results",
                        to="programs.goal",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="programs.match",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Sin iniciar"),
                            ("in_progress", "En progreso"),
                            ("done", "Completado"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="programs.match",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("milestone_due", "Milestone Vencido"),
                            ("milestone_upcoming", "Milestone Próximo"),
                            ("new_match", "Nuevo Match"),
                            ("rating_received", "Rating Recibido"),
                            ("message", "Nuevo Mensaje"),
                            ("system", "Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programs.match",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programs.milestone",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="match",
            name="mentee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentee_matches",
                to="programs.participant",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor_matches",
                to="programs.participant",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="facilitators",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "facilitator"},
                related_name="facilitated_activities",
                to="programs.participant",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_activities",
                to="programs.participant",
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("theme", models.CharField(default="General", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("designed", "Diseñado"),
                            ("ready_for_execution", "Listo para Ejecución"),
                            ("in_execution", "En Ejecución"),
                            ("under_review", "Revisión"),
                            ("closed", "Cerrado"),
                            ("draft", "Borrador"),
                            ("active", "Activo"),
                            ("paused", "Pausado"),
                            ("completed", "Completado"),
                        ],
                        default="designed",
                        max_length=30,
                    ),
                ),
                ("requires_certification", models.BooleanField(default=False)),
                ("certification_rules", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_follow_up", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="participant",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="programs.program",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="programs.program",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("entity", models.CharField(max_length=50)),
                ("entity_id", models.CharField(max_length=100)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("activity_delayed", "Actividad Atrasada"),
                            ("low_confirmation", "Baja Confirmación"),
                            ("low_attendance", "Baja Asistencia"),
                            ("pending_surveys", "Encuestas Pendientes"),
                            ("match_pending", "Match Pendiente"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("in_progress", "En Proceso"),
                            ("resolved", "Resuelta"),
                            ("dismissed", "Descartada"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("action_taken", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="programs.activity",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="programs.program",
            ),
        ),
        migrations.CreateModel(
            name="ProgramParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("administrator", "Administrador"),
                            ("instructor", "Instructor"),
                            ("participant", "Participante"),
                            ("observer", "Observador"),
                        ],
                        default="participant",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("pending", "Pendiente"),
                            ("suspended", "Suspendido"),
                            ("inactive", "Inactivo"),
                            ("deleted", "Eliminado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("invitation_sent_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("last_access_at", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_participants",
                        to="programs.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(help_text="Rango 1-5")),
                ("note", models.CharField(blank=True, max_length=240)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiments",
                        to="programs.match",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("module", "Módulo"),
                            ("satisfaction", "Satisfacción"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("questions", models.JSONField(default=list)),
                ("sent_to_count", models.IntegerField(default=0)),
                ("responses_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="programs.activity",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey",
                        to="programs.content",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vinculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mentoria", "Mentoría"),
                            ("tutoria", "Tutoría"),
                            ("equipo", "Equipo"),
                            ("coaching", "Coaching"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("pending", "Pendiente"),
                            ("inactive", "Inactiva"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculations_as_1",
                        to="programs.programparticipant",
                    ),
                ),
                (
                    "participant2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculations_as_2",
                        to="programs.programparticipant",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculations",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["match", "-created_at"], name="programs_go_match_i_25c45b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["status"], name="programs_go_status_915e93_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["match", "-created_at"], name="programs_ch_match_i_fc4532_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="programs_no_recipie_def393_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["-created_at"], name="programs_no_created_0a860f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("mentor", "mentee", "program"), name="unique_match_tuple"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programparticipant",
            unique_together={("program", "user")},
        ),
    ]
