# Generated by Django 4.2.11 on 2026-01-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duración del módulo en minutos'),
        ),
        migrations.AddField(
            model_name='content',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de fin del módulo', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='minimum_score',
            field=models.PositiveIntegerField(default=70, help_text='Puntuación mínima para aprobar (%)'),
        ),
        migrations.AddField(
            model_name='content',
            name='requires_evaluation',
            field=models.BooleanField(default=False, help_text='Si el módulo requiere evaluación'),
        ),
        migrations.AddField(
            model_name='content',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de inicio del módulo', null=True),
        ),
    ]
