# Generated by Django 4.2.11 on 2026-01-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_content_duration_minutes_content_end_date_and_more'),
    ]

    operations = [
    ]
