# Generated by Django 4.2.28 on 2026-03-13 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0003_add_module_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("leadership", "Leadership"),
                            ("tech", "Tech"),
                            ("sales", "Sales"),
                            ("diversity", "Diversity"),
                            ("operations", "Operations"),
                        ],
                        default="leadership",
                        max_length=30,
                    ),
                ),
                ("duration", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Borrador"), ("published", "Publicada")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("modules", models.JSONField(blank=True, default=list)),
                ("milestones", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("mentor_requirements", models.JSONField(blank=True, default=dict)),
                ("mentee_requirements", models.JSONField(blank=True, default=dict)),
                ("matching_rules", models.JSONField(blank=True, default=dict)),
                ("session_rules", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
