# Generated by Django 4.2.28 on 2026-04-12 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0005_notification_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programparticipant",
            name="role",
            field=models.CharField(
                choices=[
                    ("facilitator", "Facilitador"),
                    ("mentor", "Mentor"),
                    ("mentee", "Mentee"),
                    ("participant_cell", "Participante Celula"),
                    ("administrator", "Administrador"),
                    ("instructor", "Instructor"),
                    ("participant", "Participante"),
                    ("observer", "Observador"),
                ],
                default="participant_cell",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ProgramChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="programs.program",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["program", "-created_at"],
                        name="programs_pr_program_b854c2_idx",
                    )
                ],
            },
        ),
    ]
