# Generated by Django 5.2.15 on 2026-06-12 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_mentoring_sessions_and_completions'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cohort_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='design_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='program',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.programtemplate'),
        ),
    ]
