# Generated by Django 5.2.15 on 2026-07-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_alter_auditlog_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programtemplate',
            name='category',
            field=models.CharField(choices=[('leadership', 'Liderazgo'), ('women_empowerment', 'Empoderamiento Femenino'), ('diversity', 'Diversidad e Inclusión'), ('employability', 'Empleabilidad'), ('mentoring', 'Mentoría'), ('coaching', 'Coaching'), ('entrepreneurship', 'Emprendimiento'), ('tech', 'Tecnología'), ('digital_skills', 'Habilidades Digitales'), ('sales', 'Ventas'), ('operations', 'Operaciones'), ('communication', 'Comunicación'), ('public_speaking', 'Oratoria y Comunicación Pública'), ('career_development', 'Desarrollo de Carrera'), ('networking', 'Networking'), ('finance', 'Finanzas'), ('innovation', 'Innovación'), ('wellbeing', 'Bienestar y Salud Mental'), ('work_life_balance', 'Equilibrio Vida-Trabajo'), ('personal_branding', 'Marca Personal'), ('negotiation', 'Negociación'), ('team_management', 'Gestión de Equipos'), ('youth', 'Desarrollo Juvenil'), ('sustainability', 'Sostenibilidad y ESG')], default='leadership', max_length=30),
        ),
    ]
