# Generated by Django 5.2.15 on 2026-07-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_alter_programtemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtemplate',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
