# Generated by Django 5.2.15 on 2026-07-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_programtemplate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
