# Generated by Django 5.2.15 on 2026-07-14 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_content_resources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('viewed_at', models.DateTimeField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='programs.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['content', 'user'], name='programs_co_content_f8ef44_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='programs.programparticipant')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['participant', 'occurred_at'], name='programs_pa_partici_90bbec_idx')],
            },
        ),
    ]
