# Generated by Django 5.2.15 on 2026-07-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_generatedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='banner_svg',
            field=models.TextField(blank=True),
        ),
    ]
