# Generated by Django 5.2.15 on 2026-07-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_program_banner_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='banner_image',
            field=models.TextField(blank=True),
        ),
    ]
