# Generated by Django 5.2.15 on 2026-08-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='programparticipant',
            name='last_portal_access_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
