# Generated by Django 5.2.15 on 2026-08-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_programparticipant_last_portal_access_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringsession',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='location_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='modality',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'Presencial'), ('hybrid', 'Híbrido')], default='online', max_length=20),
        ),
    ]
