# Generated by Django 5.2.15 on 2026-08-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_mentoringsession_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringsession',
            name='mentee_commitment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='mentee_confidence',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='mentee_reflection',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='mentee_reflection_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='mentor_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='mentor_acknowledgment_note',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
