# Generated by Django 5.2.15 on 2026-08-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_mentoringsession_mentee_commitment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringsession',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
