# Generated by Django 5.2.9 on 2025-12-31 18:43

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("programs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email donde se enviará la invitación",
                        max_length=254,
                        verbose_name="Email del invitado",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("mentor", "Mentor"), ("mentee", "Mentee")],
                        max_length=20,
                        verbose_name="Rol asignado",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        max_length=64,
                        unique=True,
                        verbose_name="Token único de invitación",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("accepted", "Aceptada"),
                            ("expired", "Expirada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(verbose_name="Fecha de expiración"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aceptación"
                    ),
                ),
                (
                    "personal_message",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje opcional que verá el invitado",
                        null=True,
                        verbose_name="Mensaje personalizado",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_invitations",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invitado por",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_invitations",
                        to="programs.program",
                        verbose_name="Programa asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitación Pendiente",
                "verbose_name_plural": "Invitaciones Pendientes",
                "db_table": "pending_invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("validation", "Validación de Token"),
                            ("account", "Creación de Cuenta"),
                            ("linkedin", "Importación LinkedIn"),
                            ("profile", "Completar Perfil"),
                            ("config", "Configuración Específica"),
                            ("completed", "Completado"),
                        ],
                        default="validation",
                        max_length=20,
                        verbose_name="Paso actual",
                    ),
                ),
                (
                    "linkedin_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos de LinkedIn (raw)"
                    ),
                ),
                (
                    "extracted_profile",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Perfil extraído por IA"
                    ),
                ),
                (
                    "custom_data",
                    models.JSONField(default=dict, verbose_name="Datos personalizados"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress",
                        to="invitations.pendinginvitation",
                        verbose_name="Invitación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Onboarding",
                "verbose_name_plural": "Progresos de Onboarding",
                "db_table": "onboarding_progress",
            },
        ),
        migrations.AddIndex(
            model_name="pendinginvitation",
            index=models.Index(
                fields=["email", "status"], name="pending_inv_email_abb06a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendinginvitation",
            index=models.Index(fields=["token"], name="pending_inv_token_288090_idx"),
        ),
        migrations.AddIndex(
            model_name="pendinginvitation",
            index=models.Index(
                fields=["company", "status"], name="pending_inv_company_e3206c_idx"
            ),
        ),
    ]
