# Generated by Django 5.2.9 on 2025-12-31 18:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Empresa"
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "corp_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="ID Corporativo",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Industria"
                    ),
                ),
                (
                    "company_size",
                    models.CharField(blank=True, max_length=50, verbose_name="Tamaño"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Sitio Web")),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Razón Social"
                    ),
                ),
                (
                    "rut",
                    models.CharField(blank=True, max_length=12, verbose_name="RUT"),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ID Tributario"
                    ),
                ),
                (
                    "legal_address",
                    models.TextField(blank=True, verbose_name="Dirección Legal"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="Región"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Chile", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código Postal"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre Contacto"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Contacto"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono Contacto"
                    ),
                ),
                (
                    "contact_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cargo Contacto"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de Negocio"
                    ),
                ),
                (
                    "foundation_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año Fundación"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("startup", "Startup"),
                            ("growth", "Growth"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Activa"),
                            ("suspended", "Suspendida"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "is_data_complete",
                    models.BooleanField(
                        default=False, verbose_name="Información Completa"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Habilitado para Programas"
                    ),
                ),
                ("max_users", models.PositiveIntegerField(default=100)),
                ("max_programs", models.PositiveIntegerField(default=1)),
                ("max_participants", models.PositiveIntegerField(default=100)),
                ("logo_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(default="#FFD700", max_length=7)),
                ("secondary_color", models.CharField(default="#1E293B", max_length=7)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Admin"),
                            ("inspiratoria_admin", "Admin Inspiratoria"),
                            ("client", "Cliente"),
                            ("admin", "Administrador"),
                            ("facilitator_internal", "Facilitador Interno"),
                            ("facilitator_inspiratoria", "Facilitador Inspiratoria"),
                            ("mentor", "Mentor"),
                            ("mentee", "Mentee"),
                            ("participant", "Participante"),
                        ],
                        default="mentee",
                        max_length=30,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("avatar_url", models.URLField(blank=True)),
                ("is_onboarded", models.BooleanField(default=False)),
                ("onboarding_step", models.PositiveIntegerField(default=0)),
                ("can_manage_clients", models.BooleanField(default=False)),
                ("can_manage_programs", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
                ("can_manage_activities", models.BooleanField(default=False)),
                ("can_execute_matches", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=False)),
                ("can_close_programs", models.BooleanField(default=False)),
                ("can_manage_alerts", models.BooleanField(default=False)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OnboardingInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Admin"),
                            ("inspiratoria_admin", "Admin Inspiratoria"),
                            ("client", "Cliente"),
                            ("admin", "Administrador"),
                            ("facilitator_internal", "Facilitador Interno"),
                            ("facilitator_inspiratoria", "Facilitador Inspiratoria"),
                            ("mentor", "Mentor"),
                            ("mentee", "Mentee"),
                            ("participant", "Participante"),
                        ],
                        max_length=30,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("accepted", "Aceptada"),
                            ("expired", "Expirada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="companies.company",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
