# Generated by Django 4.2.20 on 2026-03-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("internal", "Interna (Inspiratoria)"),
                    ("core", "Core (Auto-registro)"),
                    ("studio", "Studio (Consultoría)"),
                ],
                default="core",
                max_length=20,
                verbose_name="Tipo de Cuenta",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="plan",
            field=models.CharField(
                choices=[
                    ("trial", "Trial (14 días)"),
                    ("starter", "Starter - $3,200/año"),
                    ("growth", "Growth - $9,600/año"),
                    ("enterprise", "Enterprise - Custom"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
    ]
