# Generated by Django 4.2.20 on 2026-03-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_account_type_alter_company_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("trial", "Trial"),
                    ("active", "Activa"),
                    ("suspended", "Suspendida"),
                    ("cancelled", "Cancelada"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
    ]
