# Generated by Django 4.2.28 on 2026-03-07 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="assigned_pm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="PM Asignado",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="contract_end",
            field=models.DateField(blank=True, null=True, verbose_name="Fin Contrato"),
        ),
        migrations.AddField(
            model_name="company",
            name="contract_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Inicio Contrato"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="internal_notes",
            field=models.TextField(blank=True, verbose_name="Notas Internas"),
        ),
        migrations.CreateModel(
            name="AccountNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "Nota General"),
                            ("call", "Llamada"),
                            ("meeting", "Reunión"),
                            ("email", "Email"),
                            ("task", "Tarea"),
                            ("decision", "Decisión"),
                            ("milestone", "Hito"),
                            ("issue", "Problema"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Fijado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Cuenta",
                "verbose_name_plural": "Notas de Cuenta",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Cambio de Estado"),
                            ("plan_change", "Cambio de Plan"),
                            ("pm_assign", "Asignación de PM"),
                            ("info_update", "Actualización de Datos"),
                            ("account_created", "Cuenta Creada"),
                            ("account_approved", "Solicitud Aprobada"),
                            ("contract_update", "Actualización de Contrato"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_changed", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción del cambio"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changelog",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Cambio",
                "verbose_name_plural": "Registros de Cambio",
                "ordering": ["-created_at"],
            },
        ),
    ]
