# Generated by Django 4.2.28 on 2026-03-07 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_assigned_pm_company_contract_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_hash",
                    models.CharField(blank=True, max_length=64, unique=True),
                ),
                (
                    "generated_email",
                    models.EmailField(max_length=254, verbose_name="Email de acceso"),
                ),
                (
                    "generated_password",
                    models.CharField(
                        max_length=128, verbose_name="Contraseña generada"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("suspended", "Suspendida"),
                            ("expired", "Expirada"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("login_count", models.PositiveIntegerField(default=0)),
                ("credentials_sent", models.BooleanField(default=False)),
                ("credentials_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studio_admin_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studio_account",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Studio",
                "verbose_name_plural": "Cuentas Studio",
                "ordering": ["-created_at"],
            },
        ),
    ]
