# Generated by Django 4.2.28 on 2026-04-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_studioaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_account_activated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_code",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
