# Generated by Django 4.2.28 on 2026-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_add_otp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="view_permissions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de vistas del dashboard que el usuario puede ver",
            ),
        ),
    ]
