# Generated by Django 4.2.28 on 2026-04-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_user_view_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
