# Generated by Django 4.2.28 on 2026-04-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_user_totp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_token",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
