# Generated by Django 4.2.28 on 2026-04-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_activation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardinginvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin_root", "Admin Root"),
                    ("inspiratoria_admin", "Admin Inspiratoria"),
                    ("coordinator", "Coordinador"),
                    ("project_manager", "Project Manager"),
                    ("billing", "Facturación"),
                    ("client", "Cliente"),
                    ("admin", "Administrador"),
                    ("facilitator_internal", "Facilitador Interno"),
                    ("facilitator_inspiratoria", "Facilitador Inspiratoria"),
                    ("mentor", "Mentor"),
                    ("mentee", "Mentee"),
                    ("participant", "Participante"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin_root", "Admin Root"),
                    ("inspiratoria_admin", "Admin Inspiratoria"),
                    ("coordinator", "Coordinador"),
                    ("project_manager", "Project Manager"),
                    ("billing", "Facturación"),
                    ("client", "Cliente"),
                    ("admin", "Administrador"),
                    ("facilitator_internal", "Facilitador Interno"),
                    ("facilitator_inspiratoria", "Facilitador Inspiratoria"),
                    ("mentor", "Mentor"),
                    ("mentee", "Mentee"),
                    ("participant", "Participante"),
                ],
                default="mentee",
                max_length=30,
            ),
        ),
    ]
