# Generated by Django 4.2.28 on 2026-04-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_add_new_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
