# Generated by Django 4.2.28 on 2026-04-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_avatar_url_to_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
