# Generated by Django 4.2.28 on 2026-04-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_logo_url_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="portal_code",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
