# Generated by Django 4.2.28 on 2026-04-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_add_portal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="headline",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
