# Generated by Django 4.2.28 on 2026-04-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0014_user_bio_user_headline_user_linkedin_url_user_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="experience_area",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="experience_level",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("masculino", "Masculino"),
                    ("femenino", "Femenino"),
                    ("no_binario", "No binario"),
                    ("prefiero_no_decir", "Prefiero no decir"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mentee_outcomes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="mentee_preference",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="mentor_objectives",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="mentor_profile_step",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="mentor_style",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="mentor_topics",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="personal_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="presentation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="session_structure",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
