# Generated by Django 4.2.28 on 2026-04-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0015_mentor_profile_extended"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mentee_challenges",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="mentee_expectations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="mentee_goals",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="mentee_interests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="mentee_profile_step",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_mentor_style",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="session_format_preference",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
