# Generated by Django 5.2.15 on 2026-07-06 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_user_mentee_challenges_user_mentee_expectations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='companies_t_created_49f5ea_idx')],
            },
        ),
    ]
